Chapter 5
yossefkatri/encryptor pull request #4
Opened 2022-03-07 13:48 UTC by yossefkatri

finished 5

2022-03-15 10:06 UTC, Shoval-Cohen requested changes

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/basicAlgorithms/ShiftMultiplyEncryption.java
> +        return "{ShiftMultiplyEncryption}";
Change it at the parent class to be class name

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/basicAlgorithms/ShiftMultiplyEncryption.java
>          //limited my key to 0-10
There is a log about this limitation?
Someone that will need to investigate the behavior of the algorithm will understand it without reading the code?

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/complexAlgorithm/DoubleEncryption.java
> +    public DoubleEncryption(EncryptionAlgorithmImpl<T> aEncryptionAlgorithm) {
Why not call it encryptionAlgorithm

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/complexAlgorithm/DoubleEncryption.java
> +        char cipherChar = encryptionAlgorithm.encryptChar(plainChar, ((DoubleKey<T>) key).getKey1());
What if the casting will not work?
If someone put key that is not DoubleKey?

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/complexAlgorithm/RepeatEncryption.java
> +        return "RepeatEncryption{"+encryptionAlgorithm+"}";
Add how many times you repeat it

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
> +        isDebug();
?

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
> +            IEncryptionAlgorithm<Integer> encryptionAlgorithm = new DoubleEncryption<>(new DoubleEncryption<>(new DoubleEncryption<>(XorEncryption.getInstance())));
What's going on? LoL

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
> +            new EncryptionLog4JLogger(fileEncryptor.getStateChangeSupport());
You don't save this logger in variable

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
> +                    stringPath = stringPath.replaceAll("\"", "");
why?

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
>                  } catch (Exception e) {
Handle all exception types

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
>              if (input == 1) {
use switch case

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/encriptionAlgorithms/basicAlgorithms/ShiftMultiplyEncryption.java
> +
Do ctrl +alt + L

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/events/DecryptionEndedEvent.java
> +     * Constructs a prototypical Event.
Add informative information

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/events/EncryptionLogEventArgs.java
> +    public Boolean isFile;
use primitive type

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/ilisteners/IDecryptionEndedListener.java
> +package ilisteners;
i?

2022-03-15 10:06 UTC, Shoval-Cohen commented on src/main/java/keys/DoubleKey.java
> +public class DoubleKey<T> implements IKey<T> {
Double key must be the same type?

2022-03-15 15:15 UTC, Shoval-Cohen requested changes
Ctrl + Alt + L

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/multiThreading/AsyncDirectoryProcessor.java
> +    private LocalDateTime getPeriod(LocalDateTime startTime) {
Read about java Duration object

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/multiThreading/AsyncDirectoryProcessor.java
> +
Empty line

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/multiThreading/AsyncDirectoryProcessor.java
> +        fileEncryptor.getStateChangeSupport().notifyEncryptionStartedListeners(this, startTime, encryptionAlgorithm.toString(), outputDirPath, originalDirPath, key.toString(), false);
break to lines

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/StateChangeSupport.java
> +        for (IDecryptionStartedListener listener :
use Java Streams as you learned in the java8 tutorial

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/FileStream.java
> +        for (int i = 0; i< (long) 262144; ++i)
????

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/FileStream.java
> +            throw new IOException("The system cannot create the directory");
||

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/FileStream.java
> +    public static void generateBigFiles(Path dir, int numOfFile) throws IOException {
Add doc

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +    }
add empty line

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +public class KeyManager {
Ctrl + Alt + L

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +        for (Integer key : keys) {
use streams
Adi makeup was here

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +    }
Empty line

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +        for (int i = 0; i < numKeys; ++i) {
Google: create random int list java

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +    }
empty line

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +        Path keyPath = Paths.get(outputPath.toString(), "key.txt");
It wil override already saved key
How do you handle it?

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/utils/KeyManager.java
> +    public  IKey<Integer> getKeys()  {
Rename to generateKeys

2022-03-15 15:15 UTC, Shoval-Cohen commented on src/main/java/encryptor.java
> +                    logger.debug("input file path:" + path + " output file path: " + outputFilepath + " key content: " + key);
use the logger built-in

2022-04-11 07:58 UTC, yossefkatri commented on src/main/java/encryptor.java
> +                    logger.debug("input file path:" + path + " output file path: " + outputFilepath + " key content: " + key);
done

2022-04-11 08:21 UTC, yossefkatri commented on src/main/java/utils/FileStream.java
> +        for (int i = 0; i< (long) 262144; ++i)
the number of time you should repeat to get about 3MB file.

2022-04-11 13:37 UTC, yossefkatri commented
done

2022-04-11 13:37 UTC, merged